### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/roman-numerals-challenge#4]
package.json code needs updating. `npm install` fails to successfully completed

**Comment by jrhorn424** [comment]
@berziiii Was this related to npmjs.org issues? Can you provide more context, maybe an error message?

**Comment by laurenfazah** [comment]
I'm pretty sure this had to do with npmjs.org issues - `npm install` is working fine for me.

**Comment by BenGitsCode** [comment]
I wasn't able to reproduce this the last three times I've come across this issue queue. Closing.
